// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.1
// source: document.proto

package document

import (
	audit "github.com/sologenic/com-fs-utils-lib/models/audit"
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentStatus int32

const (
	DocumentStatus_NOT_USED_STATUS DocumentStatus = 0
	DocumentStatus_UNPUBLISHED     DocumentStatus = 1 // Document is unpublished and in draft state
	DocumentStatus_ACTIVE          DocumentStatus = 2 // Document is active and required for users
	DocumentStatus_OUTDATED        DocumentStatus = 3 // Document is outdated and no longer required
)

// Enum value maps for DocumentStatus.
var (
	DocumentStatus_name = map[int32]string{
		0: "NOT_USED_STATUS",
		1: "UNPUBLISHED",
		2: "ACTIVE",
		3: "OUTDATED",
	}
	DocumentStatus_value = map[string]int32{
		"NOT_USED_STATUS": 0,
		"UNPUBLISHED":     1,
		"ACTIVE":          2,
		"OUTDATED":        3,
	}
)

func (x DocumentStatus) Enum() *DocumentStatus {
	p := new(DocumentStatus)
	*p = x
	return p
}

func (x DocumentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_document_proto_enumTypes[0].Descriptor()
}

func (DocumentStatus) Type() protoreflect.EnumType {
	return &file_document_proto_enumTypes[0]
}

func (x DocumentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentStatus.Descriptor instead.
func (DocumentStatus) EnumDescriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{0}
}

type DocumentState int32

const (
	DocumentState_NOT_USED_STATE DocumentState = 0
	DocumentState_TO_BE_SIGNED   DocumentState = 1
	DocumentState_SIGNED         DocumentState = 2
	DocumentState_DISPLAY_ONLY   DocumentState = 3
)

// Enum value maps for DocumentState.
var (
	DocumentState_name = map[int32]string{
		0: "NOT_USED_STATE",
		1: "TO_BE_SIGNED",
		2: "SIGNED",
		3: "DISPLAY_ONLY",
	}
	DocumentState_value = map[string]int32{
		"NOT_USED_STATE": 0,
		"TO_BE_SIGNED":   1,
		"SIGNED":         2,
		"DISPLAY_ONLY":   3,
	}
)

func (x DocumentState) Enum() *DocumentState {
	p := new(DocumentState)
	*p = x
	return p
}

func (x DocumentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentState) Descriptor() protoreflect.EnumDescriptor {
	return file_document_proto_enumTypes[1].Descriptor()
}

func (DocumentState) Type() protoreflect.EnumType {
	return &file_document_proto_enumTypes[1]
}

func (x DocumentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentState.Descriptor instead.
func (DocumentState) EnumDescriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{1}
}

type Document struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Document *DocumentDetails   `protobuf:"bytes,1,opt,name=Document,proto3" json:"Document,omitempty"`
	MetaData *metadata.MetaData `protobuf:"bytes,2,opt,name=MetaData,proto3" json:"MetaData,omitempty"` // Network is not to be assigned (documents are network agnostic)
	Audit    *audit.Audit       `protobuf:"bytes,3,opt,name=Audit,proto3" json:"Audit,omitempty"`
}

func (x *Document) Reset() {
	*x = Document{}
	if protoimpl.UnsafeEnabled {
		mi := &file_document_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetDocument() *DocumentDetails {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *Document) GetMetaData() *metadata.MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *Document) GetAudit() *audit.Audit {
	if x != nil {
		return x.Audit
	}
	return nil
}

// Key format: OrganizationID_Name_Version
type DocumentDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationID    string         `protobuf:"bytes,1,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	Name              string         `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Version           string         `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"` // Latest version of the document
	Description       string         `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	File              *File          `protobuf:"bytes,5,opt,name=File,proto3" json:"File,omitempty"`
	SignatureRequired bool           `protobuf:"varint,6,opt,name=SignatureRequired,proto3" json:"SignatureRequired,omitempty"` // if false, the document is for display/reference only
	Status            DocumentStatus `protobuf:"varint,7,opt,name=Status,proto3,enum=document.DocumentStatus" json:"Status,omitempty"`
}

func (x *DocumentDetails) Reset() {
	*x = DocumentDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_document_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentDetails) ProtoMessage() {}

func (x *DocumentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentDetails.ProtoReflect.Descriptor instead.
func (*DocumentDetails) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentDetails) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *DocumentDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DocumentDetails) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DocumentDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DocumentDetails) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *DocumentDetails) GetSignatureRequired() bool {
	if x != nil {
		return x.SignatureRequired
	}
	return false
}

func (x *DocumentDetails) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_NOT_USED_STATUS
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference string  `protobuf:"bytes,1,opt,name=Reference,proto3" json:"Reference,omitempty"` // The reference to the file
	Extension string  `protobuf:"bytes,2,opt,name=Extension,proto3" json:"Extension,omitempty"`
	Name      *string `protobuf:"bytes,3,opt,name=Name,proto3,oneof" json:"Name,omitempty"` // User defined name of the file, used as a "description" and not to reference the file
	MD5SUM    string  `protobuf:"bytes,4,opt,name=MD5SUM,proto3" json:"MD5SUM,omitempty"`   // MD5 checksum of the file for integrity verification
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_document_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *File) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *File) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *File) GetMD5SUM() string {
	if x != nil {
		return x.MD5SUM
	}
	return ""
}

type Documents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Documents []*Document `protobuf:"bytes,1,rep,name=Documents,proto3" json:"Documents,omitempty"`
	Offset    int32       `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
}

func (x *Documents) Reset() {
	*x = Documents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_document_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Documents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Documents) ProtoMessage() {}

func (x *Documents) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Documents.ProtoReflect.Descriptor instead.
func (*Documents) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{3}
}

func (x *Documents) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *Documents) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// UserDocumentCompliance is embedded in User object to track user document compliance
type UserDocumentCompliance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignedDocuments []*SignedDocument `protobuf:"bytes,1,rep,name=SignedDocuments,proto3" json:"SignedDocuments,omitempty"`
}

func (x *UserDocumentCompliance) Reset() {
	*x = UserDocumentCompliance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_document_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDocumentCompliance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDocumentCompliance) ProtoMessage() {}

func (x *UserDocumentCompliance) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDocumentCompliance.ProtoReflect.Descriptor instead.
func (*UserDocumentCompliance) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{4}
}

func (x *UserDocumentCompliance) GetSignedDocuments() []*SignedDocument {
	if x != nil {
		return x.SignedDocuments
	}
	return nil
}

type SignedDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	SignedVersion string                 `protobuf:"bytes,2,opt,name=SignedVersion,proto3" json:"SignedVersion,omitempty"` // The version of the document that was signed. This may differ from the current/latest version.
	DocumentState DocumentState          `protobuf:"varint,3,opt,name=DocumentState,proto3,enum=document.DocumentState" json:"DocumentState,omitempty"`
	SignedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=SignedAt,proto3" json:"SignedAt,omitempty"`
	FileMD5SUM    string                 `protobuf:"bytes,5,opt,name=FileMD5SUM,proto3" json:"FileMD5SUM,omitempty"` // MD5 checksum of the file that was signed
}

func (x *SignedDocument) Reset() {
	*x = SignedDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_document_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedDocument) ProtoMessage() {}

func (x *SignedDocument) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedDocument.ProtoReflect.Descriptor instead.
func (*SignedDocument) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{5}
}

func (x *SignedDocument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignedDocument) GetSignedVersion() string {
	if x != nil {
		return x.SignedVersion
	}
	return ""
}

func (x *SignedDocument) GetDocumentState() DocumentState {
	if x != nil {
		return x.DocumentState
	}
	return DocumentState_NOT_USED_STATE
}

func (x *SignedDocument) GetSignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SignedAt
	}
	return nil
}

func (x *SignedDocument) GetFileMD5SUM() string {
	if x != nil {
		return x.FileMD5SUM
	}
	return ""
}

var File_document_proto protoreflect.FileDescriptor

var file_document_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x39, 0x73, 0x6f, 0x6c,
	0x6f, 0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x2d, 0x66, 0x73, 0x2d, 0x75, 0x74,
	0x69, 0x6c, 0x73, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x33, 0x73, 0x6f, 0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69,
	0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x2d, 0x66, 0x73, 0x2d, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2d, 0x6c,
	0x69, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2f,
	0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x01, 0x0a, 0x08,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x35, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x08, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x2e, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x22, 0x0a, 0x05, 0x41, 0x75, 0x64, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x52, 0x05, 0x41, 0x75,
	0x64, 0x69, 0x74, 0x22, 0x8d, 0x02, 0x0a, 0x0f, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x4f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a,
	0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x22, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x12, 0x30, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x7c, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x78, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x45, 0x78,
	0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x16, 0x0a, 0x06, 0x4d, 0x44, 0x35, 0x53, 0x55, 0x4d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x4d, 0x44, 0x35, 0x53, 0x55, 0x4d, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x55, 0x0a, 0x09, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x30,
	0x0a, 0x09, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x5c, 0x0a, 0x16, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x42, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xe1, 0x01, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x0d, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x0d, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x08, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x69,
	0x6c, 0x65, 0x4d, 0x44, 0x35, 0x53, 0x55, 0x4d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x46, 0x69, 0x6c, 0x65, 0x4d, 0x44, 0x35, 0x53, 0x55, 0x4d, 0x2a, 0x50, 0x0a, 0x0e, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x13, 0x0a, 0x0f,
	0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10,
	0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48, 0x45, 0x44,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x02, 0x12, 0x0c,
	0x0a, 0x08, 0x4f, 0x55, 0x54, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10, 0x03, 0x2a, 0x53, 0x0a, 0x0d,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x0e, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x4f, 0x5f, 0x42, 0x45, 0x5f, 0x53, 0x49, 0x47, 0x4e, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x49, 0x47, 0x4e, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x10, 0x0a, 0x0c, 0x44, 0x49, 0x53, 0x50, 0x4c, 0x41, 0x59, 0x5f, 0x4f, 0x4e, 0x4c, 0x59, 0x10,
	0x03, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x6f, 0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x2d, 0x66, 0x73,
	0x2d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x3b,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_document_proto_rawDescOnce sync.Once
	file_document_proto_rawDescData = file_document_proto_rawDesc
)

func file_document_proto_rawDescGZIP() []byte {
	file_document_proto_rawDescOnce.Do(func() {
		file_document_proto_rawDescData = protoimpl.X.CompressGZIP(file_document_proto_rawDescData)
	})
	return file_document_proto_rawDescData
}

var file_document_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_document_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_document_proto_goTypes = []interface{}{
	(DocumentStatus)(0),            // 0: document.DocumentStatus
	(DocumentState)(0),             // 1: document.DocumentState
	(*Document)(nil),               // 2: document.Document
	(*DocumentDetails)(nil),        // 3: document.DocumentDetails
	(*File)(nil),                   // 4: document.File
	(*Documents)(nil),              // 5: document.Documents
	(*UserDocumentCompliance)(nil), // 6: document.UserDocumentCompliance
	(*SignedDocument)(nil),         // 7: document.SignedDocument
	(*metadata.MetaData)(nil),      // 8: metadata.MetaData
	(*audit.Audit)(nil),            // 9: audit.Audit
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
}
var file_document_proto_depIdxs = []int32{
	3,  // 0: document.Document.Document:type_name -> document.DocumentDetails
	8,  // 1: document.Document.MetaData:type_name -> metadata.MetaData
	9,  // 2: document.Document.Audit:type_name -> audit.Audit
	4,  // 3: document.DocumentDetails.File:type_name -> document.File
	0,  // 4: document.DocumentDetails.Status:type_name -> document.DocumentStatus
	2,  // 5: document.Documents.Documents:type_name -> document.Document
	7,  // 6: document.UserDocumentCompliance.SignedDocuments:type_name -> document.SignedDocument
	1,  // 7: document.SignedDocument.DocumentState:type_name -> document.DocumentState
	10, // 8: document.SignedDocument.SignedAt:type_name -> google.protobuf.Timestamp
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_document_proto_init() }
func file_document_proto_init() {
	if File_document_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_document_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Document); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_document_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_document_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_document_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Documents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_document_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDocumentCompliance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_document_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_document_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_document_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_document_proto_goTypes,
		DependencyIndexes: file_document_proto_depIdxs,
		EnumInfos:         file_document_proto_enumTypes,
		MessageInfos:      file_document_proto_msgTypes,
	}.Build()
	File_document_proto = out.File
	file_document_proto_rawDesc = nil
	file_document_proto_goTypes = nil
	file_document_proto_depIdxs = nil
}
