// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: document.proto

package document

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	audit "github.com/sologenic/com-fs-utils-lib/models/audit"
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentStatus int32

const (
	DocumentStatus_NOT_USED_STATUS DocumentStatus = 0
	DocumentStatus_UNPUBLISHED     DocumentStatus = 1 // Document is unpublished and in draft state
	DocumentStatus_ACTIVE          DocumentStatus = 2 // Document is active and required for users
	DocumentStatus_OUTDATED        DocumentStatus = 3 // Document is outdated and no longer required
)

// Enum value maps for DocumentStatus.
var (
	DocumentStatus_name = map[int32]string{
		0: "NOT_USED_STATUS",
		1: "UNPUBLISHED",
		2: "ACTIVE",
		3: "OUTDATED",
	}
	DocumentStatus_value = map[string]int32{
		"NOT_USED_STATUS": 0,
		"UNPUBLISHED":     1,
		"ACTIVE":          2,
		"OUTDATED":        3,
	}
)

func (x DocumentStatus) Enum() *DocumentStatus {
	p := new(DocumentStatus)
	*p = x
	return p
}

func (x DocumentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_document_proto_enumTypes[0].Descriptor()
}

func (DocumentStatus) Type() protoreflect.EnumType {
	return &file_document_proto_enumTypes[0]
}

func (x DocumentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentStatus.Descriptor instead.
func (DocumentStatus) EnumDescriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{0}
}

type DocumentState int32

const (
	DocumentState_NOT_USED_STATE DocumentState = 0
	DocumentState_TO_BE_SIGNED   DocumentState = 1
	DocumentState_SIGNED         DocumentState = 2
	DocumentState_DISPLAY_ONLY   DocumentState = 3
)

// Enum value maps for DocumentState.
var (
	DocumentState_name = map[int32]string{
		0: "NOT_USED_STATE",
		1: "TO_BE_SIGNED",
		2: "SIGNED",
		3: "DISPLAY_ONLY",
	}
	DocumentState_value = map[string]int32{
		"NOT_USED_STATE": 0,
		"TO_BE_SIGNED":   1,
		"SIGNED":         2,
		"DISPLAY_ONLY":   3,
	}
)

func (x DocumentState) Enum() *DocumentState {
	p := new(DocumentState)
	*p = x
	return p
}

func (x DocumentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentState) Descriptor() protoreflect.EnumDescriptor {
	return file_document_proto_enumTypes[1].Descriptor()
}

func (DocumentState) Type() protoreflect.EnumType {
	return &file_document_proto_enumTypes[1]
}

func (x DocumentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentState.Descriptor instead.
func (DocumentState) EnumDescriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{1}
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *DocumentDetails       `protobuf:"bytes,1,opt,name=Document,proto3" json:"Document,omitempty"`
	MetaData      *metadata.MetaData     `protobuf:"bytes,2,opt,name=MetaData,proto3" json:"MetaData,omitempty"` // Network is not to be assigned (documents are network agnostic)
	Audit         *audit.Audit           `protobuf:"bytes,3,opt,name=Audit,proto3" json:"Audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetDocument() *DocumentDetails {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *Document) GetMetaData() *metadata.MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *Document) GetAudit() *audit.Audit {
	if x != nil {
		return x.Audit
	}
	return nil
}

// Key format: OrganizationID_File.MD5SUM
type DocumentDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrganizationID    string                 `protobuf:"bytes,1,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Version           string                 `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"` // Latest version of the document
	Description       string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	File              *File                  `protobuf:"bytes,5,opt,name=File,proto3" json:"File,omitempty"`
	SignatureRequired bool                   `protobuf:"varint,6,opt,name=SignatureRequired,proto3" json:"SignatureRequired,omitempty"` // if false, the document is for display/reference only
	Status            DocumentStatus         `protobuf:"varint,7,opt,name=Status,proto3,enum=document.DocumentStatus" json:"Status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DocumentDetails) Reset() {
	*x = DocumentDetails{}
	mi := &file_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentDetails) ProtoMessage() {}

func (x *DocumentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentDetails.ProtoReflect.Descriptor instead.
func (*DocumentDetails) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentDetails) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *DocumentDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DocumentDetails) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DocumentDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DocumentDetails) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *DocumentDetails) GetSignatureRequired() bool {
	if x != nil {
		return x.SignatureRequired
	}
	return false
}

func (x *DocumentDetails) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_NOT_USED_STATUS
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=Reference,proto3" json:"Reference,omitempty"` // The reference to the file
	Name          *string                `protobuf:"bytes,3,opt,name=Name,proto3,oneof" json:"Name,omitempty"`     // User defined name of the file, used as a "description" and not to reference the file
	MD5SUM        string                 `protobuf:"bytes,4,opt,name=MD5SUM,proto3" json:"MD5SUM,omitempty"`       // MD5 checksum of the file for integrity verification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *File) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *File) GetMD5SUM() string {
	if x != nil {
		return x.MD5SUM
	}
	return ""
}

type Documents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=Documents,proto3" json:"Documents,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Documents) Reset() {
	*x = Documents{}
	mi := &file_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Documents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Documents) ProtoMessage() {}

func (x *Documents) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Documents.ProtoReflect.Descriptor instead.
func (*Documents) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{3}
}

func (x *Documents) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *Documents) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// UserDocumentCompliance is embedded in User object to track user document compliance
type UserDocumentCompliance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SignedDocuments []*SignedDocument      `protobuf:"bytes,1,rep,name=SignedDocuments,proto3" json:"SignedDocuments,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserDocumentCompliance) Reset() {
	*x = UserDocumentCompliance{}
	mi := &file_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDocumentCompliance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDocumentCompliance) ProtoMessage() {}

func (x *UserDocumentCompliance) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDocumentCompliance.ProtoReflect.Descriptor instead.
func (*UserDocumentCompliance) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{4}
}

func (x *UserDocumentCompliance) GetSignedDocuments() []*SignedDocument {
	if x != nil {
		return x.SignedDocuments
	}
	return nil
}

// SignedDocuments is the request body for batch sign
type SignedDocuments struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SignedDocuments []*SignedDocument      `protobuf:"bytes,1,rep,name=SignedDocuments,proto3" json:"SignedDocuments,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignedDocuments) Reset() {
	*x = SignedDocuments{}
	mi := &file_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedDocuments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedDocuments) ProtoMessage() {}

func (x *SignedDocuments) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedDocuments.ProtoReflect.Descriptor instead.
func (*SignedDocuments) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{5}
}

func (x *SignedDocuments) GetSignedDocuments() []*SignedDocument {
	if x != nil {
		return x.SignedDocuments
	}
	return nil
}

type SignedDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	SignedVersion string                 `protobuf:"bytes,2,opt,name=SignedVersion,proto3" json:"SignedVersion,omitempty"` // The version of the document that was signed. This may differ from the current/latest version.
	DocumentState DocumentState          `protobuf:"varint,3,opt,name=DocumentState,proto3,enum=document.DocumentState" json:"DocumentState,omitempty"`
	SignedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=SignedAt,proto3" json:"SignedAt,omitempty"`
	FileMD5SUM    string                 `protobuf:"bytes,5,opt,name=FileMD5SUM,proto3" json:"FileMD5SUM,omitempty"` // MD5 checksum of the file that was signed
	TXID          string                 `protobuf:"bytes,6,opt,name=TXID,proto3" json:"TXID,omitempty"`             // Transaction ID of the signed document (e.g. from the blockchain)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedDocument) Reset() {
	*x = SignedDocument{}
	mi := &file_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedDocument) ProtoMessage() {}

func (x *SignedDocument) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedDocument.ProtoReflect.Descriptor instead.
func (*SignedDocument) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{6}
}

func (x *SignedDocument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignedDocument) GetSignedVersion() string {
	if x != nil {
		return x.SignedVersion
	}
	return ""
}

func (x *SignedDocument) GetDocumentState() DocumentState {
	if x != nil {
		return x.DocumentState
	}
	return DocumentState_NOT_USED_STATE
}

func (x *SignedDocument) GetSignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SignedAt
	}
	return nil
}

func (x *SignedDocument) GetFileMD5SUM() string {
	if x != nil {
		return x.FileMD5SUM
	}
	return ""
}

func (x *SignedDocument) GetTXID() string {
	if x != nil {
		return x.TXID
	}
	return ""
}

var File_document_proto protoreflect.FileDescriptor

const file_document_proto_rawDesc = "" +
	"\n" +
	"\x0edocument.proto\x12\bdocument\x1a\x1fgoogle/protobuf/timestamp.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\x1a3sologenic/com-fs-utils-lib/models/audit/audit.proto\x1a\x1bbuf/validate/validate.proto\"\x9d\x01\n" +
	"\bDocument\x12=\n" +
	"\bDocument\x18\x01 \x01(\v2\x19.document.DocumentDetailsB\x06\xbaH\x03\xc8\x01\x01R\bDocument\x12.\n" +
	"\bMetaData\x18\x02 \x01(\v2\x12.metadata.MetaDataR\bMetaData\x12\"\n" +
	"\x05Audit\x18\x03 \x01(\v2\f.audit.AuditR\x05Audit\"\xca\x02\n" +
	"\x0fDocumentDetails\x120\n" +
	"\x0eOrganizationID\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eOrganizationID\x12\x1e\n" +
	"\x04Name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x04Name\x12#\n" +
	"\aVersion\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18 R\aVersion\x12*\n" +
	"\vDescription\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x04R\vDescription\x12*\n" +
	"\x04File\x18\x05 \x01(\v2\x0e.document.FileB\x06\xbaH\x03\xc8\x01\x01R\x04File\x12,\n" +
	"\x11SignatureRequired\x18\x06 \x01(\bR\x11SignatureRequired\x12:\n" +
	"\x06Status\x18\a \x01(\x0e2\x18.document.DocumentStatusB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06Status\"\xa7\x01\n" +
	"\x04File\x120\n" +
	"\tReference\x18\x01 \x01(\tB\x12\xbaH\x0fr\r\x18\x80\x02:\x05gs://\x88\x01\x01R\tReference\x12!\n" +
	"\x04Name\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01H\x00R\x04Name\x88\x01\x01\x120\n" +
	"\x06MD5SUM\x18\x04 \x01(\tB\x18\xbaH\x15r\x132\x11^[a-fA-F0-9]{32}$R\x06MD5SUMB\a\n" +
	"\x05_NameJ\x04\b\x02\x10\x03R\tExtension\"U\n" +
	"\tDocuments\x120\n" +
	"\tDocuments\x18\x01 \x03(\v2\x12.document.DocumentR\tDocuments\x12\x16\n" +
	"\x06Offset\x18\x02 \x01(\x05R\x06Offset\"\xff\x01\n" +
	"\x16UserDocumentCompliance\x12M\n" +
	"\x0fSignedDocuments\x18\x01 \x03(\v2\x18.document.SignedDocumentB\t\xbaH\x06\x92\x01\x03\x10\x80\x01R\x0fSignedDocuments:\x95\x01\xbaH\x91\x01\x1a\x8e\x01\n" +
	"+user_document_compliance.unique_file_md5sum\x12+The list should not contain duplicate items\x1a2this.SignedDocuments.map(d, d.FileMD5SUM).unique()\"\xf1\x01\n" +
	"\x0fSignedDocuments\x12N\n" +
	"\x0fSignedDocuments\x18\x01 \x03(\v2\x18.document.SignedDocumentB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x10@R\x0fSignedDocuments:\x8d\x01\xbaH\x89\x01\x1a\x86\x01\n" +
	"#signed_documents.unique_file_md5sum\x12+The list should not contain duplicate items\x1a2this.SignedDocuments.map(d, d.FileMD5SUM).unique()\"\xcf\x02\n" +
	"\x0eSignedDocument\x12\x1e\n" +
	"\x04Name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x04Name\x12/\n" +
	"\rSignedVersion\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18 R\rSignedVersion\x12I\n" +
	"\rDocumentState\x18\x03 \x01(\x0e2\x17.document.DocumentStateB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\rDocumentState\x126\n" +
	"\bSignedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bSignedAt\x128\n" +
	"\n" +
	"FileMD5SUM\x18\x05 \x01(\tB\x18\xbaH\x15r\x132\x11^[a-fA-F0-9]{32}$R\n" +
	"FileMD5SUM\x12/\n" +
	"\x04TXID\x18\x06 \x01(\tB\x1b\xbaH\x18\xd8\x01\x01r\x13\x18\x80\x012\x0e^[a-fA-F0-9]+$R\x04TXID*P\n" +
	"\x0eDocumentStatus\x12\x13\n" +
	"\x0fNOT_USED_STATUS\x10\x00\x12\x0f\n" +
	"\vUNPUBLISHED\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\f\n" +
	"\bOUTDATED\x10\x03*S\n" +
	"\rDocumentState\x12\x12\n" +
	"\x0eNOT_USED_STATE\x10\x00\x12\x10\n" +
	"\fTO_BE_SIGNED\x10\x01\x12\n" +
	"\n" +
	"\x06SIGNED\x10\x02\x12\x10\n" +
	"\fDISPLAY_ONLY\x10\x03B5Z3github.com/sologenic/com-fs-document-model;documentb\x06proto3"

var (
	file_document_proto_rawDescOnce sync.Once
	file_document_proto_rawDescData []byte
)

func file_document_proto_rawDescGZIP() []byte {
	file_document_proto_rawDescOnce.Do(func() {
		file_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_document_proto_rawDesc), len(file_document_proto_rawDesc)))
	})
	return file_document_proto_rawDescData
}

var file_document_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_document_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_document_proto_goTypes = []any{
	(DocumentStatus)(0),            // 0: document.DocumentStatus
	(DocumentState)(0),             // 1: document.DocumentState
	(*Document)(nil),               // 2: document.Document
	(*DocumentDetails)(nil),        // 3: document.DocumentDetails
	(*File)(nil),                   // 4: document.File
	(*Documents)(nil),              // 5: document.Documents
	(*UserDocumentCompliance)(nil), // 6: document.UserDocumentCompliance
	(*SignedDocuments)(nil),        // 7: document.SignedDocuments
	(*SignedDocument)(nil),         // 8: document.SignedDocument
	(*metadata.MetaData)(nil),      // 9: metadata.MetaData
	(*audit.Audit)(nil),            // 10: audit.Audit
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
}
var file_document_proto_depIdxs = []int32{
	3,  // 0: document.Document.Document:type_name -> document.DocumentDetails
	9,  // 1: document.Document.MetaData:type_name -> metadata.MetaData
	10, // 2: document.Document.Audit:type_name -> audit.Audit
	4,  // 3: document.DocumentDetails.File:type_name -> document.File
	0,  // 4: document.DocumentDetails.Status:type_name -> document.DocumentStatus
	2,  // 5: document.Documents.Documents:type_name -> document.Document
	8,  // 6: document.UserDocumentCompliance.SignedDocuments:type_name -> document.SignedDocument
	8,  // 7: document.SignedDocuments.SignedDocuments:type_name -> document.SignedDocument
	1,  // 8: document.SignedDocument.DocumentState:type_name -> document.DocumentState
	11, // 9: document.SignedDocument.SignedAt:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_document_proto_init() }
func file_document_proto_init() {
	if File_document_proto != nil {
		return
	}
	file_document_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_document_proto_rawDesc), len(file_document_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_document_proto_goTypes,
		DependencyIndexes: file_document_proto_depIdxs,
		EnumInfos:         file_document_proto_enumTypes,
		MessageInfos:      file_document_proto_msgTypes,
	}.Build()
	File_document_proto = out.File
	file_document_proto_goTypes = nil
	file_document_proto_depIdxs = nil
}
