// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: document-grpc.proto

package document

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentID struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationID string                 `protobuf:"bytes,1,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	MD5SUM         string                 `protobuf:"bytes,2,opt,name=MD5SUM,proto3" json:"MD5SUM,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DocumentID) Reset() {
	*x = DocumentID{}
	mi := &file_document_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentID) ProtoMessage() {}

func (x *DocumentID) ProtoReflect() protoreflect.Message {
	mi := &file_document_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentID.ProtoReflect.Descriptor instead.
func (*DocumentID) Descriptor() ([]byte, []int) {
	return file_document_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentID) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *DocumentID) GetMD5SUM() string {
	if x != nil {
		return x.MD5SUM
	}
	return ""
}

type Filter struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrganizationID    string                 `protobuf:"bytes,1,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	Name              *string                `protobuf:"bytes,2,opt,name=Name,proto3,oneof" json:"Name,omitempty"`
	SignatureRequired *bool                  `protobuf:"varint,3,opt,name=SignatureRequired,proto3,oneof" json:"SignatureRequired,omitempty"`
	Status            *DocumentStatus        `protobuf:"varint,4,opt,name=Status,proto3,enum=document.DocumentStatus,oneof" json:"Status,omitempty"`
	Offset            *int32                 `protobuf:"varint,5,opt,name=Offset,proto3,oneof" json:"Offset,omitempty"`
	Limit             *int32                 `protobuf:"varint,6,opt,name=Limit,proto3,oneof" json:"Limit,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_document_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_document_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_document_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *Filter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Filter) GetSignatureRequired() bool {
	if x != nil && x.SignatureRequired != nil {
		return *x.SignatureRequired
	}
	return false
}

func (x *Filter) GetStatus() DocumentStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return DocumentStatus_NOT_USED_STATUS
}

func (x *Filter) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *Filter) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

var File_document_grpc_proto protoreflect.FileDescriptor

const file_document_grpc_proto_rawDesc = "" +
	"\n" +
	"\x13document-grpc.proto\x12\bdocument\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0edocument.proto\x1a\x1bbuf/validate/validate.proto\"p\n" +
	"\n" +
	"DocumentID\x120\n" +
	"\x0eOrganizationID\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eOrganizationID\x120\n" +
	"\x06MD5SUM\x18\x02 \x01(\tB\x18\xbaH\x15r\x132\x11^[a-fA-F0-9]{32}$R\x06MD5SUM\"\xe0\x02\n" +
	"\x06Filter\x120\n" +
	"\x0eOrganizationID\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eOrganizationID\x12$\n" +
	"\x04Name\x18\x02 \x01(\tB\v\xbaH\b\xd8\x01\x01r\x03\x18\x80\x01H\x00R\x04Name\x88\x01\x01\x121\n" +
	"\x11SignatureRequired\x18\x03 \x01(\bH\x01R\x11SignatureRequired\x88\x01\x01\x12?\n" +
	"\x06Status\x18\x04 \x01(\x0e2\x18.document.DocumentStatusB\b\xbaH\x05\x82\x01\x02\x10\x01H\x02R\x06Status\x88\x01\x01\x12$\n" +
	"\x06Offset\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x03R\x06Offset\x88\x01\x01\x12%\n" +
	"\x05Limit\x18\x06 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00H\x04R\x05Limit\x88\x01\x01B\a\n" +
	"\x05_NameB\x14\n" +
	"\x12_SignatureRequiredB\t\n" +
	"\a_StatusB\t\n" +
	"\a_OffsetB\b\n" +
	"\x06_Limit2\xad\x01\n" +
	"\x0fDocumentService\x121\n" +
	"\x03Get\x12\x14.document.DocumentID\x1a\x12.document.Document\"\x00\x12/\n" +
	"\x04List\x12\x10.document.Filter\x1a\x13.document.Documents\"\x00\x126\n" +
	"\x06Upsert\x12\x12.document.Document\x1a\x16.google.protobuf.Empty\"\x00B5Z3github.com/sologenic/com-fs-document-model;documentb\x06proto3"

var (
	file_document_grpc_proto_rawDescOnce sync.Once
	file_document_grpc_proto_rawDescData []byte
)

func file_document_grpc_proto_rawDescGZIP() []byte {
	file_document_grpc_proto_rawDescOnce.Do(func() {
		file_document_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_document_grpc_proto_rawDesc), len(file_document_grpc_proto_rawDesc)))
	})
	return file_document_grpc_proto_rawDescData
}

var file_document_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_document_grpc_proto_goTypes = []any{
	(*DocumentID)(nil),    // 0: document.DocumentID
	(*Filter)(nil),        // 1: document.Filter
	(DocumentStatus)(0),   // 2: document.DocumentStatus
	(*Document)(nil),      // 3: document.Document
	(*Documents)(nil),     // 4: document.Documents
	(*emptypb.Empty)(nil), // 5: google.protobuf.Empty
}
var file_document_grpc_proto_depIdxs = []int32{
	2, // 0: document.Filter.Status:type_name -> document.DocumentStatus
	0, // 1: document.DocumentService.Get:input_type -> document.DocumentID
	1, // 2: document.DocumentService.List:input_type -> document.Filter
	3, // 3: document.DocumentService.Upsert:input_type -> document.Document
	3, // 4: document.DocumentService.Get:output_type -> document.Document
	4, // 5: document.DocumentService.List:output_type -> document.Documents
	5, // 6: document.DocumentService.Upsert:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_document_grpc_proto_init() }
func file_document_grpc_proto_init() {
	if File_document_grpc_proto != nil {
		return
	}
	file_document_proto_init()
	file_document_grpc_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_document_grpc_proto_rawDesc), len(file_document_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_document_grpc_proto_goTypes,
		DependencyIndexes: file_document_grpc_proto_depIdxs,
		MessageInfos:      file_document_grpc_proto_msgTypes,
	}.Build()
	File_document_grpc_proto = out.File
	file_document_grpc_proto_goTypes = nil
	file_document_grpc_proto_depIdxs = nil
}
