syntax = "proto3";

package document;

option go_package = "github.com/sologenic/com-fs-document-model;document";

import "document.proto";

service DocumentService {
    rpc Get (DocumentID) returns (Document) {}
    rpc List (Filter) returns (Documents) {}
    rpc Upsert (Document) returns (DocumentID) {}
}

message DocumentID {
    string DocumentID = 1;
}

message Filter {
    string OrganizationID = 1;
    optional DocumentType DocumentType = 2;
    optional bool SignatureRequired = 3;
    optional bool IsActive = 4;
    optional int32 Offset = 5;
    optional int32 Limit = 6;
}